version: '3'

services:

  membership-api-app:
    build: .                          # Use Dockerfile to build image
    image: membership-api:latest      # Name of the resulting image
    container_name: application       # Name of the resulting container
    ports:                            # External/internal port mapping:
      - 8085:8085
    depends_on:                       # Service(s) that this service depends on:
      membership-api-db:
          condition: service_healthy
    networks:                         # Local network for services (containers)
      - network

  membership-api-db:
    image: mysql:latest               # Image used to create container (from Docker registry)
    container_name: database
    environment:                      # Environment variables for the service (container):
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=memberships
    healthcheck:                      # Command that, when ran, proves service (container) is healthy
      test: [ "CMD", "echo", "MySQL database container is healthy" ]
    networks:
      - network

networks:

  network:
    driver: bridge
