version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
#    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=memberships
    ports:
      - "3308:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: